-- create database
CREATE DATABASE IF NOT EXISTS mm_tests;

-- create tables
CREATE TABLE IF NOT EXISTS mm_tests.tbl_a (id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, name VARCHAR(255));
CREATE TABLE IF NOT EXISTS mm_tests.tbl_b (id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, name VARCHAR(255));
